title: "LaTeX コードの可読性・保守性を高めるコマンドデザイン"
summary: ""
topics: ["latex"]
published: false
price: 0 # 有料の場合200〜5000
chapters:
  - intro.md
  - readability.md
  - good_commands.md
  - process.md
  - extended_commands.md
  - misc_commands.md
  - criteria.md
  - conclusion.md
